# Generated by Django 5.0.2 on 2025-05-24 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billsplit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='billsplit',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='receipt',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billsplit',
            name='person_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('is_paid', models.BooleanField(default=False)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
        ),
        migrations.AlterField(
            model_name='billsplit',
            name='items',
            field=models.ManyToManyField(blank=True, to='receipts.receiptitem'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
