# Generated by Django 5.0.2 on 2025-05-24 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_remove_billsplit_created_at_remove_billsplit_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='sharing_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
